---
roles:
  - name: githubixx.ansible_role_wireguard
  - name: geerlingguy.helm
  - src: https://github.com/ansible-community/ansible-vault.git
    name: ansible-community.ansible-vault
    scm: git
    version: master
collections:
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: master
  - name: ansible.utils
  - name: community.general
  - name: ansible.posix
  - name: kubernetes.core
