---
- name: Install WireGuard
  hosts: server
  become: true
  tags:
    - wireguard
  roles:
    - role: githubixx.ansible_role_wireguard

- name: Install Helm
  hosts: server
  become: true
  tags:
    - helm
  roles:
    - role: geerlingguy.helm
      vars:
        helm_arch: arm64
