---
- name: Install and configure Vault Server
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ansible-community.ansible-vault
      vault_install_remotely: true
      vault_raft_group_name: server
      vault_architecture_map:
        aarch64: arm64
      vault_tcp_listeners:
        - vault_address: 0.0.0.0
          vault_port: 8200
          vault_cluster_address: 0.0.0.0:8201
          vault_tls_disable: true
          vault_tls_disable_client_certs: true
      vault_api_addr: http://{{ in_host }}:8200
      vault_tls_disable: true
      vault_tls_disable_client_certs: true
