---
- name: Update and install packages
  hosts: all
  become: true
  tasks:
    - name: Update packages
      apt:
        name: "*"
        update_cache: yes
    - name: Install packages
      apt:
        name:
          - unzip
- name: Certificates
  hosts: all
  become: true
  tasks:
    - name: Ensure /etc/vault/tls directory exists
      file:
        path: /etc/vault/tls
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Copy CA cert
      copy:
        src: ./certificates/ca.crt
        dest: /etc/vault/tls
        owner: root
        group: root
        mode: '0644'
    - name: Copy CA cert to shared dir
      copy:
        src: ./certificates/ca.crt
        dest: /usr/local/share/ca-certificates
        owner: root
        group: root
        mode: '0644'
    - name: Copy server cert
      copy:
        src: ./certificates/server.crt
        dest: /etc/vault/tls
        owner: root
        group: root
        mode: '0644'
    - name: Copy server key
      copy:
        src: ./certificates/server.key
        dest: /etc/vault/tls
        owner: root
        group: root
        mode: '0644'
    - name: Update CA certificates
      shell:
        cmd: update-ca-certificates
- name: Install and configure Vault Server
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ansible-community.ansible-vault
      vars:
        vault_log_level: debug
        vault_architecture_map:
          aarch64: arm64
        vault_install_remotely: true
        vault_tcp_listeners:
          - vault_address: 0.0.0.0
            vault_port: 8200
            vault_cluster_address: 0.0.0.0:8201
            vault_tls_disable: false
            vault_tls_certs_path: /etc/vault/tls
            vault_tls_cert_file: server.crt
            vault_tls_private_path: /etc/vault/tls
            vault_tls_key_file: server.key
            vault_tls_min_version: tls12
            vault_tls_require_and_verify_client_cert: false
            vault_tls_disable_client_certs: true
        vault_api_addr: https://{{ ansible_hostname }}.servers.default.oraclevcn.com:8200
        vault_cluster_addr: http://{{ ansible_hostname }}.servers.default.oraclevcn.com:8201
        vault_raft_group_name: server
        vault_raft_cluster_members:
          - peer: internal-lb
            api_addr: https://internal-lb.servers.default.oraclevcn.com:8200
            leader_ca_cert_file : /etc/vault/tls/ca.crt
            leader_client_cert_file: /etc/vault/tls/server.crt
            leader_client_key_file: /etc/vault/tls/server.key
        vault_ocikms: true
        vault_ocikms_key_id: ocid1.key.oc1.eu-frankfurt-1.ens6g353aaebq.abtheljtsnokaxa4f7srxwogpvsxqj36h2ikzn4kjuwwcteaewcj4lcxpxlq
        vault_ocikms_crypto_endpoint: https://ens6g353aaebq-crypto.kms.eu-frankfurt-1.oraclecloud.com
        vault_ocikms_management_endpoint: https://ens6g353aaebq-management.kms.eu-frankfurt-1.oraclecloud.com
