---
server:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new
  hosts:
    inst-9qqrl-instancepool20240719213914:
      ansible_host: 130.61.28.235
    inst-v1pst-instancepool20240719213914:
      ansible_host: 130.61.40.111
    inst-wfs4r-instancepool20240719213914:
      ansible_host: 130.61.98.86