---
ansible_user: ubuntu
ansible_ssh_private_key_file: certificates/ssh-key-2024-03-16.key

first_server_internal_ip: 10.0.0.22
external_lb_ip: 34.160.96.247
internal_lb_ip: 10.20.0.2
key_value_store_ip: 10.206.0.5
key_value_store_name: key-value-store
key_value_store_user: admin

k3s_version: v1.29.3+k3s1
token: "mytoken"  # Use ansible vault if you want to keep it secret
api_endpoint: "{{ first_server_internal_ip }}"
extra_server_args: ""
extra_agent_args: ""
